### ISSUE TITLE
Schedule order selection is empty

### ISSUE THREAD

**Issue by iTzMeRafa** [tastyigniter/ti-theme-orange#17] opened 2020-09-20 12:15 UTC
**Expected behavior:**
Options of dates a customer can order for delivery in advance (which is defined in the backend "Allow Pre-order for Delivery")

**Actual behavior:**
Empty options list, both for date and time

**Reproduce steps:**
Pretty new installation and did not change anything in `localBox/timeslot` before testing

**Version:**
2.1.1

**Additional Information:**
![timeslot_both_1](https://user-images.githubusercontent.com/36051055/93711046-321b7280-fb4b-11ea-9413-ba32a0baa233.png)    

![timeslot_both_2](https://user-images.githubusercontent.com/36051055/93711050-35aef980-fb4b-11ea-9b26-a8d127af8ec0.png)

`$orderDateTime` is initialized.
What surprises me is that both select tags have no option values. Maybe this is the issue?

**Comment by sampoyigi** [comment] 2020-09-24 23:21
@ryanmitchell can you have a look at this?

**Comment by ryanmitchell** [comment] 2020-09-25 04:59
I noticed this yesterday but it's version 2.1.1 - are we not focusing on the 3.x branch?

**Comment by sampoyigi** [comment] 2020-09-25 14:17
Yes @iTzMeRafa got the version number wrong, its actually v3

**Comment by ryanmitchell** [comment] 2020-09-25 14:45
@iTzMeRafa can you give me screenshots of your location settings so I can try and replicate your setup and the issue?

**Comment by iTzMeRafa** [comment] 2020-09-25 14:51
@ryanmitchell do you mean screenshots of my delivery areas?

**Comment by ryanmitchell** [comment] 2020-09-25 14:53
@iTzMeRafa No, your opening time and location settings so I can ensure I have the same settings as you to get to the cause of the issue.

**Comment by iTzMeRafa** [comment] 2020-09-25 14:54
![image](https://user-images.githubusercontent.com/36051055/94282051-ac833280-ff4f-11ea-987a-d385f35b75f3.png)

![image](https://user-images.githubusercontent.com/36051055/94282083-b6a53100-ff4f-11ea-852a-6ac33b5621c2.png)

![image](https://user-images.githubusercontent.com/36051055/94282115-be64d580-ff4f-11ea-80dd-186d2fc50353.png)

**Comment by ryanmitchell** [comment] 2020-09-25 15:02
Yes, I can see the problem. Your closing time is on the next day! If you set it to 23:59 it works fine, but as things stand setting it to anything after that will cause an error.

@sampoyigi how could we handle this better - I hadn't ever considered opening hours that cross midnight.

**Comment by sampoyigi** [comment] 2020-09-25 15:51
@ryanmitchell good catch! Just had a look at the logic for generating timeslot and right its not handling next day closing hours. To handle midnight hours better, the logic here `WorkingSchedule::getTimeslot()` and here `WorkingPeriod::timeslot()` probably needs to change. `WorkingRange` class already has a `endsNextDay` method to check for midnight hours.

**Comment by ryanmitchell** [comment] 2020-09-25 17:29
I pushed 2 PRs (sorry did it through GitHub web), let me know if those work for you @iTzMeRafa and if you are happy with approach @sampoyigi

**Closed** 2020-10-01 15:52 UTC
